FROM php:8.1-apache

RUN apt-get update \
    && apt-get install -y \
        libicu-dev \
        libzip-dev \
        zip \
        unzip \
    && docker-php-ext-install \
        pdo_mysql \
        intl \
        zip \
    && a2enmod \
        rewrite

RUN curl -sSk https://getcomposer.org/installer | php -- --disable-tls && \
   mv composer.phar /usr/local/bin/composer


COPY . /var/www/

COPY ./docker/apache.conf /etc/apache2/sites-available/000-default.conf


WORKDIR /var/www

COPY composer.json composer.lock ./

RUN composer install --no-dev --no-scripts --no-autoloader && composer dump-autoload --optimize

ENTRYPOINT ["bash", "./docker/docker.sh"]

EXPOSE 80